apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: store-monitoring
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
      evaluation_interval: 15s

    scrape_configs:
      - job_name: 'otel-collector'
        static_configs:
          - targets: ['otel-collector.store-otel:8889']

    remote_write:
      - url: "http://mimir.store-monitoring:9009/api/v1/push"
        headers:
          X-Scope-OrgID: "qim-info"
        name: "mimir-long-term-storage"
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: prometheus
  namespace: store-monitoring
spec:
  serviceName: prometheus
  replicas: 1
  selector:
    matchLabels:
      app: prometheus
  template:
    metadata:
      labels:
        app: prometheus
    spec:
      containers:
      - name: prometheus
        image: prom/prometheus:v2.49.0
        args:
        - --config.file=/etc/prometheus/prometheus.yml
        - --storage.tsdb.retention.time=24h
        - --web.enable-lifecycle
        ports:
        - containerPort: 9090
          name: http
        volumeMounts:
        - name: config
          mountPath: /etc/prometheus
        - name: prometheus-data
          mountPath: /prometheus
      volumes:
      - name: config
        configMap:
          name: prometheus-config
  volumeClaimTemplates:
  - metadata:
      name: prometheus-data
    spec:
      accessModes: ["ReadWriteOnce"]
      resources:
        requests:
          storage: 5Gi
---
apiVersion: v1
kind: Service
metadata:
  name: prometheus
  namespace: store-monitoring
spec:
  ports:
  - port: 9090
    targetPort: http
    name: http
  selector:
    app: prometheus
