apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: store-monitoring
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
      evaluation_interval: 15s
    
    scrape_configs:
      - job_name: 'opentelemetry'
        static_configs:
          - targets: ['otel-collector.store-otel:8889']
      - job_name: 'trivy'
        static_configs:
          - targets: ['trivy-operator.trivy-system:8080']
      - job_name: 'falco'
        static_configs:
          - targets: ['falco-falcosidekick.falco:2801']
      - job_name: 'jmeter'
        static_configs:
          - targets: ['host.minikube.internal:9270']
    
    remote_write:
      - url: "http://34.163.114.227/mimir/api/v1/push"
        headers:
          X-Scope-OrgID: "qim-info"
        name: "mimir-long-term-storage"
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app.kubernetes.io/instance: otel-mastery-all
  name: prometheus
  namespace: store-monitoring
spec:
  podManagementPolicy: OrderedReady
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: prometheus
  serviceName: prometheus
  template:
    metadata:
      labels:
        app: prometheus
    spec:
      containers:
      - args:
        - --config.file=/etc/prometheus/prometheus.yml
        - --storage.tsdb.retention.time=24h
        - --web.enable-lifecycle
        - --storage.tsdb.path=/prometheus/data
        image: prom/prometheus:v2.49.0
        imagePullPolicy: IfNotPresent
        name: prometheus
        ports:
        - containerPort: 9090
          name: http
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /etc/prometheus
          name: config
        - mountPath: /prometheus
          name: prometheus-data
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext:
        fsGroup: 65534
      terminationGracePeriodSeconds: 30
      volumes:
      - configMap:
          defaultMode: 420
          name: prometheus-config
        name: config
  updateStrategy:
    rollingUpdate:
      partition: 0
    type: RollingUpdate
  volumeClaimTemplates:
  - apiVersion: v1
    kind: PersistentVolumeClaim
    metadata:
      name: prometheus-data
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 5Gi
      volumeMode: Filesystem
---
apiVersion: v1
kind: Service
metadata:
  name: prometheus
  namespace: store-monitoring
spec:
  ports:
  - port: 9090
    targetPort: http
    name: http
  selector:
    app: prometheus
