apiVersion: v1
kind: ConfigMap
metadata:
  name: tempo-config
  namespace: store-monitoring
data:
  tempo.yaml: |
    server:
      http_listen_port: 3200

    distributor:
      receivers:
        otlp:
          protocols:
            http:
              endpoint: "0.0.0.0:4318"

    storage:
      trace:
        backend: local
        local:
          path: /tmp/tempo/traces
    
    compactor:
      compaction:
        block_retention: 48h

    ingester:
      max_block_duration: 5m

    metrics_generator:
      storage:
        path: /tmp/tempo/metrics
      registry:
        external_labels:
          source: tempo
          cluster: demo
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: tempo
  namespace: store-monitoring
spec:
  serviceName: tempo
  replicas: 1
  selector:
    matchLabels:
      app: tempo
  template:
    metadata:
      labels:
        app: tempo
    spec:
      containers:
      - name: tempo
        image: grafana/tempo:2.3.0
        args:
        - -config.file=/etc/tempo/tempo.yaml
        ports:
        - containerPort: 4318
          name: otlp-http
        - containerPort: 3200
          name: http
        volumeMounts:
        - name: config
          mountPath: /etc/tempo
        - name: data
          mountPath: /tmp/tempo
      volumes:
      - name: config
        configMap:
          name: tempo-config
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 10Gi
---
apiVersion: v1
kind: Service
metadata:
  name: tempo
  namespace: store-monitoring
spec:
  ports:
  - port: 4318
    targetPort: 4318
    name: otlp-http
  - port: 3200
    targetPort: 3200
    name: tempo
  selector:
    app: tempo