apiVersion: v1
kind: ConfigMap
metadata:
  name: tempo-config
  namespace: store-monitoring
data:
  tempo.yaml: |
    server:
      http_listen_port: 3200

    distributor:
      receivers:
        otlp:
          protocols:
            grpc:
            http:
              endpoint: 0.0.0.0:4318

    storage:
      trace:
        backend: local
        local:
          path: /data/tempo

    compactor:
      compaction:
        block_retention: 24h

    metrics_generator:
      processor:
        service_graphs:
          dimensions: ["cluster", "namespace"]
        local_blocks: {} 
      storage:
        path: /data/tempo/metrics
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: tempo
  namespace: store-monitoring
spec:
  serviceName: tempo
  replicas: 1
  selector:
    matchLabels:
      app: tempo
  template:
    metadata:
      labels:
        app: tempo
    spec:
      containers:
        - name: tempo
          image: grafana/tempo:2.4.0
          args:
            - --config.file=/etc/tempo/tempo.yaml
          ports:
            - containerPort: 3200
            - containerPort: 9095
          volumeMounts:
            - name: config
              mountPath: /etc/tempo
            - name: data
              mountPath: /data/tempo
      volumes:
        - name: config
          configMap:
            name: tempo-config
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 10Gi
---
apiVersion: v1
kind: Service
metadata:
  name: tempo
  namespace: store-monitoring
spec:
  ports:
    - name: tempo-http
      port: 3200
      targetPort: 3200
    - name: otlp-http
      port: 4318
      targetPort: 4318
  selector:
    app: tempo
