stages:
  - checkout
  - load_test
  - deploy

variables:
  DOCKER_TLS_CERTDIR: ""
  DOCKER_DRIVER: overlay2

# 1️⃣ Checkout
checkout:
  stage: checkout
  script:
    - echo "Repository at $CI_PROJECT_DIR"
  rules:
    - when: always

# 6️⃣ Deploy & ArgoCD sync
deploy:
  stage: deploy
  tags: [shell]
  script:
    - argocd login "$ARGOCD_SERVER" \
        --username "$ARGOCD_USERNAME" \
        --password "$ARGOCD_PASSWORD" \
        --insecure 
    - argocd app sync otel-mastery
  only:
    - master
