apiVersion: v1
kind: Service
metadata:
  name: kafka
  namespace: store-infra
  labels:
    app: kafka
spec:
  ports:
    - port: 9092
      targetPort: 9092
  selector:
    app: kafka
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka
  namespace: store-infra
  labels:
    app: kafka
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka
  template:
    metadata:
      labels:
        app: kafka
    spec:
      initContainers:
      - name: wait-for-zookeeper
        image: busybox:latest
        imagePullPolicy: IfNotPresent
        command: ['sh', '-c', 'until nc -z zookeeper.store-infra 2181; do echo "Waiting for zookeeper..."; sleep 5; done;']
      containers:
      - name: kafka
        image: bitnami/kafka:3.4.0-debian-11-r21
        imagePullPolicy: IfNotPresent
        env:
        - name: ALLOW_PLAINTEXT_LISTENER
          value: "yes"
        - name: KAFKA_CFG_BROKER_ID
          value: "1"
        - name: KAFKA_ZOOKEEPER_CONNECT
          value: "zookeeper.store-infra:2181"
        - name: KAFKA_LISTENERS
          value: "PLAINTEXT://:9092"
        - name: KAFKA_ADVERTISED_LISTENERS
          value: "PLAINTEXT://kafka.store-infra:9092"
        ports:
        - containerPort: 9092

