apiVersion: apps/v1
kind: Deployment
metadata:
  name: inventory-management
  namespace: store-app
  labels:
    app: inventory-management
spec:
  replicas: 1
  selector:
    matchLabels:
      app: inventory-management
  template:
    metadata:
      labels:
        app: inventory-management
    spec:
      containers:
      - name: inventory-management
        image: melekbadreddine/inventory:latest
        ports:
        - containerPort: 3004
        env:
        - name: POSTGRES_URL
          value: "postgres://postgres:postgres@postgres.store-infra:5432/orderdb?sslmode=disable"
        - name: KAFKA_BROKERS
          value: "kafka.store-infra:9092"
        - name: KAFKA_TOPIC
          value: "order-confirmation"
---
apiVersion: v1
kind: Service
metadata:
  name: inventory-management
  namespace: store-app
spec:
  selector:
    app: inventory-management
  ports:
    - protocol: TCP
      port: 3004
      targetPort: 3004
      nodePort: 31204
  type: NodePort
