apiVersion: apps/v1
kind: Deployment
metadata:
  name: inventory-management
  namespace: store-app
  labels:
    app: inventory-management
spec:
  replicas: 1
  selector:
    matchLabels:
      app: inventory-management
  template:
    metadata:
      labels:
        app: inventory-management
      annotations:
        instrumentation.opentelemetry.io/inject-go: "true"
        instrumentation.opentelemetry.io/otel-go-auto-target-exe: "/app/inventory-management"
        instrumentation.opentelemetry.io/go-auto-include-dependencies: "true"
    spec:
      containers:
      - name: inventory-management
        image: melekbadreddine/inventory:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 3004
        env:
        - name: POSTGRES_URL
          value: "postgres://postgres:postgres@postgres.store-infra:5432/orderdb?sslmode=disable"
        - name: KAFKA_BROKERS
          value: "kafka.store-infra:9092"
        - name: KAFKA_TOPIC
          value: "order-confirmation"
        - name: OTEL_EXPORTER_OTLP_ENDPOINT
          value: "http://otel-collector.store-otel:4318"
        - name: OTEL_SERVICE_NAME
          value: "inventory-management"
        - name: OTEL_EXPORTER_OTLP_PROTOCOL
          value: "http/protobuf"
        - name: OTEL_TRACES_SAMPLER
          value: "parentbased_always_on"
        - name: OTEL_METRICS_ENABLED
          value: "true"
        - name: OTEL_LOGS_ENABLED
          value: "true"
        - name: OTEL_LOGS_EXPORTER
          value: "otlp"
---
apiVersion: v1
kind: Service
metadata:
  name: inventory-management
  namespace: store-app
spec:
  selector:
    app: inventory-management
  ports:
    - protocol: TCP
      port: 3004
      targetPort: 3004
      nodePort: 31204
  type: NodePort
