apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-processing
  namespace: store-app
  labels:
    app: order-processing
spec:
  replicas: 3
  selector:
    matchLabels:
      app: order-processing
  template:
    metadata:
      labels:
        app: order-processing
    spec:
      containers:
      - name: order-processing
        image: melekbadreddine/orders:latest
        ports:
        - containerPort: 3003
        env:
        - name: SPRING_DATASOURCE_URL
          value: "jdbc:postgresql://postgres.store-infra:5432/orderdb"
        - name: SPRING_DATASOURCE_USERNAME
          value: "postgres"
        - name: SPRING_DATASOURCE_PASSWORD
          value: "postgres"
        - name: kafka.bootstrap-servers
          value: "kafka.store-infra:9092"
        - name: spring.kafka.bootstrap-servers
          value: "kafka.store-infra:9092"
---
apiVersion: v1
kind: Service
metadata:
  name: order-processing
  namespace: store-app
spec:
  selector:
    app: order-processing
  ports:
    - protocol: TCP
      port: 3003
      targetPort: 3003
  type: ClusterIP

