apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-catalog
  namespace: store-app
  labels:
    app: product-catalog
spec:
  replicas: 1
  selector:
    matchLabels:
      app: product-catalog
  template:
    metadata:
      labels:
        app: product-catalog
      annotations:
        instrumentation.opentelemetry.io/inject-go: "true"
    spec:
      containers:
      - name: product-catalog
        image: melekbadreddine/products:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 3001
        env:
        - name: MONGO_URI
          value: "mongodb://mongodb.store-infra:27017"
        - name: KAFKA_BROKER
          value: "kafka.store-infra:9092"
        - name: PORT
          value: "3001"
        - name: OTEL_EXPORTER_OTLP_ENDPOINT
          value: "http://otel-collector.store-otel:4318"
        - name: OTEL_SERVICE_NAME
          value: "product-catalog"
---
apiVersion: v1
kind: Service
metadata:
  name: product-catalog
  namespace: store-app
spec:
  selector:
    app: product-catalog
  ports:
    - protocol: TCP
      port: 3001
      targetPort: 3001
      nodePort: 31201
  type: NodePort

