apiVersion: apps/v1
kind: Deployment
metadata:
  name: shopping-cart
  namespace: store-app
  labels:
    app: shopping-cart
spec:
  replicas: 1
  selector:
    matchLabels:
      app: shopping-cart
  template:
    metadata:
      labels:
        app: shopping-cart
      annotations:
        instrumentation.opentelemetry.io/inject-java: "true"
        instrumentation.opentelemetry.io/instrumentation: "multi-lang-instrumentation"
    spec:
      containers:
      - name: shopping-cart
        image: melekbadreddine/cart:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 3002
        env:
        - name: SPRING_REDIS_HOST
          value: "redis.store-infra"
        - name: kafka.bootstrap-servers
          value: "kafka.store-infra:9092"
        - name: OTEL_EXPORTER_OTLP_ENDPOINT
          value: "http://otel-collector.store-otel:4318"
        - name: OTEL_SERVICE_NAME
          value: "shopping-cart"
        - name: OTEL_EXPORTER_OTLP_PROTOCOL
          value: "http/protobuf"
        - name: OTEL_TRACES_SAMPLER
          value: "parentbased_always_on"
        - name: OTEL_METRICS_ENABLED
          value: "true"
        - name: OTEL_LOGS_ENABLED
          value: "true"
        - name: OTEL_LOGS_EXPORTER
          value: "otlp"
---
apiVersion: v1
kind: Service
metadata:
  name: shopping-cart
  namespace: store-app
spec:
  selector:
    app: shopping-cart
  ports:
    - protocol: TCP
      port: 3002
      targetPort: 3002
      nodePort: 31202
  type: NodePort

