apiVersion: apps/v1
kind: Deployment
metadata:
  name: store-ui
  namespace: store-app
  labels:
    app: store-ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: store-ui
  template:
    metadata:
      labels:
        app: store-ui
      annotations:
        instrumentation.opentelemetry.io/inject-nodejs: "true"
        instrumentation.opentelemetry.io/instrumentation: "multi-lang-instrumentation"
    spec:
      containers:
      - name: store-ui
        image: melekbadreddine/store:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 4200
        env:
        - name: OTEL_EXPORTER_OTLP_ENDPOINT
          value: "http://otel-collector.store-otel:4318"
        - name: OTEL_SERVICE_NAME
          value: "store-ui"
        - name: OTEL_EXPORTER_OTLP_PROTOCOL
          value: "http/protobuf"
        - name: OTEL_TRACES_SAMPLER
          value: "parentbased_always_on"
        - name: OTEL_METRICS_ENABLED
          value: "true"
        - name: OTEL_LOGS_ENABLED
          value: "true"
        - name: OTEL_LOGS_EXPORTER
          value: "otlp"
---
apiVersion: v1
kind: Service
metadata:
  name: store-ui
  namespace: store-app
spec:
  selector:
    app: store-ui
  ports:
    - protocol: TCP
      port: 4200
      targetPort: 4200
      nodePort: 31200
  type: NodePort


