apiVersion: apps/v1
kind: Deployment
metadata:
  name: store-ui
  namespace: store-app
  labels:
    app: store-ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: store-ui
  template:
    metadata:
      labels:
        app: store-ui
    spec:
      containers:
      - name: store-ui
        image: melekbadreddine/store:latest
        ports:
        - containerPort: 4200
---
apiVersion: v1
kind: Service
metadata:
  name: store-ui
  namespace: store-app
spec:
  selector:
    app: store-ui
  ports:
    - protocol: TCP
      port: 4200
      targetPort: 4200
      nodePort: 31200
  type: NodePort


