apiVersion: v1
kind: ConfigMap
metadata:
  name: otel-collector-config
  namespace: store-otel
data:
  config.yaml: |
    receivers:
      k8s_events:
        namespaces: []

      otlp:
        protocols:
          http:
            endpoint: "0.0.0.0:4318"

    processors:
      attributes/logs:
        actions:
          - action: insert
            key: trace_id
            from_attribute: trace_id
          - action: insert
            key: span_id
            from_attribute: span_id

      attributes:
        actions:
          - action: insert
            key: loki.attribute.labels
            value: event.domain, event.name

      resource:
        attributes:
          - action: insert
            key: loki.resource.labels
            value: service.name, service.namespace

      k8sattributes:
        auth_type: serviceAccount
        passthrough: false
        extract:
          metadata:
            - k8s.pod.name
            - k8s.namespace.name
            - k8s.deployment.name

      batch:
        timeout: 10s
        send_batch_size: 1024

      memory_limiter:
        check_interval: 1s
        limit_mib: 1024

    exporters:
      logging:
        loglevel: warn
      prometheus:
        endpoint: "0.0.0.0:8889"
      loki:
        endpoint: "http://34.163.114.227/loki/loki/api/v1/push"
        timeout: 30s
      otlphttp:
        endpoint: "http://34.163.114.227/tempo"
        timeout: 30s
        tls:
          insecure: true

    extensions:
      health_check:
        endpoint: "0.0.0.0:13133"

    service:
      extensions: [health_check]
      pipelines:
        metrics:
          receivers: [otlp]
          processors: [k8sattributes, memory_limiter, batch]
          exporters: [prometheus]
        logs:
          receivers: [otlp, k8s_events]
          processors: [attributes/logs, k8sattributes, memory_limiter, batch]
          exporters: [loki]
        traces:
          receivers: [otlp]
          processors: [k8sattributes, memory_limiter, batch]
          exporters: [otlphttp]