apiVersion: v1
kind: ConfigMap
metadata:
  name: otel-collector-config
  namespace: store-otel
data:
  config.yaml: |
    receivers:
      k8s_events:
        namespaces: []

      otlp:
        protocols:
          http:
            endpoint: "0.0.0.0:4318"

      hostmetrics:
        collection_interval: 10s
        scrapers:
          cpu: {}
          load: {}
          memory: {}
          disk: {}
          filesystem:
            exclude_mount_points:
              match_type: strict
              mount_points:
                - /usr/lib/modules
                - /data
                - /tmp/hostpath_pv
                - /tmp/hostpath-provisioner

    processors:
      attributes/logs:
        actions:
          - action: insert
            key: trace_id
            from_attribute: trace_id
          - action: insert
            key: span_id
            from_attribute: span_id

      attributes:
        actions:
          - action: insert
            key: loki.attribute.labels
            value: event.domain, event.name
      
      resource:
        attributes:
          - action: insert
            key: loki.resource.labels
            value: service.name, service.namespace

      k8sattributes:
        auth_type: serviceAccount
        passthrough: false
        extract:
          metadata:
            - k8s.pod.name
            - k8s.namespace.name
            - k8s.deployment.name

      batch:
        timeout: 10s
        send_batch_size: 1024
      memory_limiter:
        check_interval: 1s
        limit_mib: 1024

    exporters:
      logging:
        loglevel: info
      prometheus:
        endpoint: "0.0.0.0:8889"
      loki:
        endpoint: "http://34.65.239.174/loki/loki/api/v1/push" 
      otlphttp:
        endpoint: "http://34.65.239.174/tempo"
        tls:
          insecure: true

    extensions:
      health_check:
        endpoint: "0.0.0.0:13133"

    service:
      extensions: [health_check]
      pipelines:
        metrics:
          receivers: [otlp, hostmetrics]
          processors: [k8sattributes, memory_limiter, batch]
          exporters: [prometheus]
        logs:
          receivers: [otlp, k8s_events]
          processors: [attributes/logs, k8sattributes, memory_limiter, batch]
          exporters: [loki]
        traces:
          receivers: [otlp]
          processors: [k8sattributes, memory_limiter, batch]
          exporters: [otlphttp]
