apiVersion: v1
kind: ConfigMap
metadata:
  name: otel-collector-config
  namespace: store-otel
data:
  config.yaml: |
    receivers:
      otlp:
        protocols:
          grpc:
            endpoint: "0.0.0.0:4317"
          http:
            endpoint: "0.0.0.0:4318"

      hostmetrics:
        collection_interval: 10s
        scrapers:
          cpu: {}
          load: {}
          memory: {}
          disk: {}
          filesystem:
            exclude_mount_points:
              match_type: strict
              mount_points:
                - /usr/lib/modules
                - /data
                - /tmp/hostpath_pv
                - /tmp/hostpath-provisioner

    processors:
      k8sattributes:
        auth_type: serviceAccount
        passthrough: false
        extract:
          metadata:
            - k8s.pod.name
            - k8s.namespace.name
            - k8s.deployment.name
      batch:
        timeout: 10s
        send_batch_size: 1024
      memory_limiter:
        check_interval: 1s
        limit_mib: 1024

    exporters:
      logging:
        loglevel: debug
      prometheus:
        endpoint: "0.0.0.0:8889"
      loki:
        endpoint: "http://loki.store-monitoring:3100/loki/api/v1/push"
      otlphttp:
        endpoint: "http://tempo.store-monitoring:4318"
        tls:
          insecure: true

    extensions:
      health_check:
        endpoint: "0.0.0.0:13133"

    service:
      extensions: [health_check]
      telemetry:
        logs:
          level: debug
      pipelines:
        metrics:
          receivers: [otlp, hostmetrics]
          processors: [k8sattributes, memory_limiter, batch]
          exporters: [prometheus]
        logs:
          receivers: [otlp]
          processors: [memory_limiter, batch]
          exporters: [loki]
        traces:
          receivers: [otlp]
          processors: [memory_limiter, batch]
          exporters: [logging, otlphttp]
