apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - minio.yaml      # Minio first (used by Mimir)
  - loki.yaml
  - prometheus.yaml
  - tempo.yaml
  - mimir.yaml
  - grafana.yaml