apiVersion: v1
kind: ConfigMap
metadata:
  name: mimir-config
  namespace: store-monitoring
data:
  mimir.yaml: |
    server:
      http_listen_port: 9009
    memberlist:
      bind_port: 7946
      join_members: []
    blocks_storage:
      backend: s3
      s3:
        bucket_name: mimir-data
        endpoint: minio:9000
        access_key_id: minio
        secret_access_key: minio123
        insecure: true
    ingester:
      ring:
        instance_addr: 127.0.0.1
        kvstore:
          store: memberlist
        replication_factor: 1
    compactor:
      data_dir: /tmp/mimir/compactor
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mimir
  namespace: store-monitoring
spec:
  serviceName: mimir
  replicas: 1
  selector:
    matchLabels:
      app: mimir
  template:
    metadata:
      labels:
        app: mimir
    spec:
      containers:
      - name: mimir
        image: grafana/mimir:2.10.1
        args:
          - "-target=all"
          - "-config.file=/etc/mimir/mimir.yaml"
        ports:
        - containerPort: 9009
          name: http
        volumeMounts:
          - name: config
            mountPath: /etc/mimir
          - name: data
            mountPath: /tmp/mimir
      volumes:
      - name: config
        configMap:
          name: mimir-config
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      accessModes: ["ReadWriteOnce"]
      resources:
        requests:
          storage: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  name: mimir
  namespace: store-monitoring
spec:
  ports:
    - port: 9009
      targetPort: http
  selector:
    app: mimir
