apiVersion: opentelemetry.io/v1alpha1
kind: Instrumentation
metadata:
  name: multi-lang-instrumentation
  namespace: store-otel
spec:
  exporter:
    endpoint: "http://otel-collector.store-otel:4318"
  propagators:
    - tracecontext
    - baggage
  sampler:
    type: parentbased_traceidratio
    argument: "1"
  go:
    image: otel/autoinstrumentation-go:v0.21.0 
    env:
      - name: OTEL_EXPORTER_OTLP_ENDPOINT
        value: "http://otel-collector.store-otel:4318"