apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - rbac.yaml       # RBAC first (ServiceAccount, ClusterRole)
  - config.yaml     # ConfigMap for Collector
  - service.yaml    # Service
  - deployment.yaml # Collector Deployment
  - network.yaml    # NetworkPolicy
  - instrumentation.yaml