version: '3.8'
services:
  mongodb:
    image: mongo:5.0
    pull_policy: if_not_present
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  postgres:
    image: postgres:latest
    pull_policy: if_not_present
    container_name: postgres
    environment:
      - POSTGRES_DB=orderdb
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
      
  redis:
    image: redis:latest
    pull_policy: if_not_present
    container_name: redis
    ports:
      - "6379:6379"

  zookeeper:
    image: bitnami/zookeeper:latest
    pull_policy: if_not_present
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    ports:
      - "2181:2181"

  kafka:
    image: bitnami/kafka:latest
    pull_policy: if_not_present
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_LISTENERS=PLAINTEXT://:9092
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
    depends_on:
      - zookeeper

  product-catalog:
    image: melekbadreddine/products:latest
    pull_policy: if_not_present
    container_name: products
    ports:
      - "3001:3001"
    environment:
      - MONGO_URI=mongodb://mongodb:27017
      - KAFKA_BROKER=kafka:9092
      - PORT=3001
    depends_on:
      - mongodb
      - kafka
      
  shopping-cart:
    image: melekbadreddine/cart:latest
    pull_policy: if_not_present
    container_name: cart
    ports:
      - "3002:3002"
    environment:
      - SPRING_REDIS_HOST=redis
      - kafka.bootstrap-servers=kafka:9092
    depends_on:
      - redis
      - kafka

  order-processing:
    image: melekbadreddine/orders:latest
    pull_policy: if_not_present
    container_name: orders
    ports:
      - "3003:3003"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/orderdb
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - kafka.bootstrap-servers=kafka:9092
    depends_on:
      - kafka
      - postgres

  inventory-management:
    image: melekbadreddine/inventory:latest
    pull_policy: if_not_present
    container_name: inventory
    ports:
      - "3004:3004"
    environment:
      - POSTGRES_URL=postgres://postgres:postgres@postgres:5432/orderdb?sslmode=disable
      - KAFKA_BROKERS=kafka:9092
      - KAFKA_TOPIC=order-confirmation
    depends_on:
      - postgres
      - kafka
      
  store-ui:
    image: melekbadreddine/store:latest
    pull_policy: if_not_present
    container_name: store
    ports:
      - "4200:4200"
    depends_on:
      - product-catalog
      - shopping-cart
      - order-processing
      - inventory-management

volumes:
  mongo-data:
  postgres-data:
