---
- name: Build applications
  hosts: build
  vars:
    src_dir: "../../../src"

  tasks:
    - name: Build Go applications
      command: go build -v
      loop:
        - inventory-management
        - product-catalog
      args:
        chdir: "{{ src_dir }}/{{ item }}"
      environment:
        PATH: "{{ ansible_env.PATH }}:/usr/local/go/bin"

    - name: Build Spring Boot applications
      command: mvn clean package
      loop:
        - shopping-cart
        - order-processing
      args:
        chdir: "{{ src_dir }}/{{ item }}"

    - name: Install Angular dependencies
      npm:
        path: "{{ src_dir }}/store-ui"
        state: present

    - name: Build Angular application
      command: npm run build
      args:
        chdir: "{{ src_dir }}/store-ui"
